### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by loberthor** [vdm-io/Joomla-Component-Builder#706]
### Steps to reproduce the issue
Empty joomla site, web installation fail, upload package fail, url installation fail.

### Expected result

Installing the component

### Actual result

Warning
Copy file failed
×
Error
Error installing component

### System information (as much as possible)

PHP Built On | Linux w-15.th.seeweb.it 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64
Database Type | mysql
Database Version | 5.6.45
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.18-1+0~20200515.59+debian9~1.gbp12fa4f
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.25 Stable [ Amani ] 02-March-2021 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

 

### Additional comments
Folders permissions ok

**Comment by denovoit** [comment]
Are you trying to install JCB or a component you have created in JCB? If you have problems installing JCB, then check your max upload filesize. JCB needs a max upload size of minimum 10MB. Max upload file size default server settings are normally 2MB. Another issue could be a wrong path to your tmp folder. Check in system->Systeminformation and see in the folder tab, if you have write permission to all the folders. 

If it's a component, then what browser are you using? I've had similar issues on Safari. Changed to Firefox, and after that I had no issue compiling and installing my components.

**Comment by Llewellynvdm** [comment]
@loberthor let us know if your still not having success... with some screenshots, I will close this issue in a few days if we don't get more feedback.

**Comment by loberthor** [comment]
I was trayn to install JCB.
In php configuration i have 32mb max size.
I really don't know what is wrong, is the first time i see one issue like this.
I olso have tried to install : https://github.com/vdm-io/Joomla-Component-Builder/archive/08d529aba970a882e096393b34bf3eb53ad1536f.zip seen in another post, but the server get the same error.

**Comment by Llewellynvdm** [comment]
I am also not sure what is the issue here.

I install JCB on new blank installs all the time, and I never get this error... so my best guess at this point is that this is a php limitation, or server limitation... not sure where to start. You said you've got the upload to 32MB, but there is more than one value to update in the php.ini file... so check these values:
```
upload_max_filesize = 32M
post_max_size = 12M
memory_limit = 512M
max_input_time = 800
max_execution_time = 120
```

Some of these values are very high... and yet I use even higher values. Reality JCB is a development tool, and not ideal for production servers... JCB works best in a local development environment where you can push the boundaries a little.

I deploy JCB with the following Docker compose file all the time for testing:
```yml
version: '2'

services:
  JCB_joomla:
    # image created for this task
    image: vdmio/joomla:3.9.25-Stable
    container_name: JCB_joomla
    restart: unless-stopped
    environment:
      WEBSITEDOMAIN: localhost
      WEBSITESNAME: "JCB checker"
      WEBSITESUNAME: "Your Name"
      WEBSITESUSERNAME: somename
      WEBSITESUSERPASS: somepassword
      WEBSITESPASSRESET: 0
      WEBSITESEMAIL: "joomla@vdm.io"
      WEBSITESADDPATCHTESTER: 0
      DBDRIVER: mysqli
      DBHOST: JCB_mysql
      DBUSER: somedbname
      DBPASS: somedbpass
      DBROOTPASS: somedbpassword
      DBNAME: joomla
      DBPREFIX: vdm
      SMTPHOST: JCB_mailcatcher
      STARTUP_COMMAND_1: deploy_joomla
    links:
      - JCB_mysql
      - JCB_mailcatcher
    depends_on:
      - JCB_mysql
    volumes:
       - JCB_web-data:/var/www/html
    ports:
      - 8080:80
      - 4443:443

  JCB_mysql:
    image: mysql:5.7
    container_name: JCB_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: somedbpassword
    volumes:
       - JCB_db-data:/var/lib/mysql

  JCB_mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped
    container_name: JCB_mailcatcher
    ports:
      - 8089:1080

volumes:
    JCB_db-data:
    JCB_web-data:
```
This is not for production but just for testing and working with JCB locally...
